/* Copyright (C) 2019-2021 Julian Valentin, LTeX Development Community
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package org.bsplines.ltexls.parsing.latex

import org.bsplines.ltexls.parsing.DummyGenerator

@Suppress("LargeClass")
object LatexAnnotatedTextBuilderDefaults {
  val defaultLatexCommandSignatures: List<LatexCommandSignature> = run {
    val list: MutableList<LatexCommandSignature> = mutableListOf(
      LatexCommandSignature("\\ac{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Ac{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\ac[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Ac[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\ac*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Ac*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\ac*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Ac*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\aca{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Aca{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\aca[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Aca[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\aca*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Aca*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\aca*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Aca*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acap{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acap{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acap[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acap[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acap*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acap*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acap*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acap*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acf{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acf{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acf[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acf[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acf*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acf*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acf*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acf*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acfp{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acfp{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acfp[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acfp[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acfp*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acfp*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acfp*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acfp*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acl{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acl{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acl[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acl[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acl*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acl*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acl*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acl*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\aclp{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Aclp{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\aclp[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Aclp[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\aclp*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Aclp*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\aclp*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Aclp*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acp{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acp{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acp[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acp[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acp*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acp*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acp*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acp*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acreset{}"),
      LatexCommandSignature("\\acresetall"),
      LatexCommandSignature("\\acs{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acs{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acs[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acs[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acs*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acs*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acs*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acs*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acsetup{}"),
      LatexCommandSignature("\\acsp{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acsp{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acsp[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acsp[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acsp*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acsp*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acsp*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Acsp*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\acuse{}"),
      LatexCommandSignature("\\acuseall"),
      LatexCommandSignature("\\addbibresource{}"),
      LatexCommandSignature("\\addcontentsline{}{}{}"),
      LatexCommandSignature("\\addtocontents{}"),
      LatexCommandSignature("\\addtocounter{}{}"),
      LatexCommandSignature("\\addtokomafont{}{}"),
      LatexCommandSignature("\\@addtoreset{}{}"),
      LatexCommandSignature("\\addtotheorempostheadhook{}"),
      LatexCommandSignature("\\addxcontentsline{}{}{}"),
      LatexCommandSignature("\\algdef{}[]{}{}"),
      LatexCommandSignature("\\algnewcommand{}{}"),
      LatexCommandSignature("\\algrenewcommand{}{}"),
      LatexCommandSignature("\\arabic{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\AtBeginEnvironment{}{}"),
      LatexCommandSignature("\\AtEndEnvironment{}{}"),
      LatexCommandSignature("\\autocite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\autocite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\autocite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Autocite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Autocite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Autocite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\autocite*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\autocite*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\autocite*[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Autocite*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Autocite*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Autocite*[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature(
        "\\autocites{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\autocites{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\autocites{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\autocites{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\autocites{}{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\autocites()()[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\autocites()()[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\autocites()()[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\autocites()()[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\autocites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites{}{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites()()[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites()()[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites()()[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites()()[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Autocites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature("\\automark{}"),
      LatexCommandSignature("\\automark[]{}"),
      LatexCommandSignature("\\automark*{}"),
      LatexCommandSignature("\\automark*[]{}"),
      LatexCommandSignature("\\autopageref{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\autopageref*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\autoref{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\autoref*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\babeltags{}"),
      LatexCommandSignature("\\bibitem{}"),
      LatexCommandSignature("\\bibliography{}"),
      LatexCommandSignature("\\bibliographystyle{}"),
      LatexCommandSignature("\\captionof{}"),
      LatexCommandSignature("\\captionsetup{}"),
      LatexCommandSignature("\\captionsetup[]{}"),
      LatexCommandSignature("\\cite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\cite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\cite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Cite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Cite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Cite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\cite*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\cite*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\cite*[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citealp{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citealp[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citealp*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citealp*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citealt{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citealt[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citealt*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citealt*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeauthor{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeauthor[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeauthor[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Citeauthor{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Citeauthor[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Citeauthor[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeauthor*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeauthor*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeauthor*[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Citeauthor*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Citeauthor*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Citeauthor*[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citedate{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citedate[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citedate[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citedate*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citedate*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citedate*[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citep{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citep[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citep*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citep*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature(
        "\\cites{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\cites{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\cites{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\cites{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\cites{}{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\cites()()[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\cites()()[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\cites()()[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\cites()()[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\cites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites{}{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites()()[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites()()[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites()()[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites()()[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Cites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature("\\citet{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citet[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citet*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citet*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citetitle{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citetitle[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citetitle[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citetitle*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citetitle*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citetitle*[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeurl{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeurl[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeurl[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeyear{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeyear[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeyear[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeyear*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeyear*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\citeyear*[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\clearfield{}"),
      LatexCommandSignature("\\color{}"),
      LatexCommandSignature("\\color[]{}"),
      LatexCommandSignature("\\colorbox{}"),
      LatexCommandSignature("\\colorlet{}{}"),
      LatexCommandSignature("\\counterwithin{}{}"),
      LatexCommandSignature("\\counterwithin*{}{}"),
      LatexCommandSignature("\\counterwithout{}{}"),
      LatexCommandSignature("\\counterwithout*{}{}"),
      LatexCommandSignature("\\cref{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Cref{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\crefname{}{}{}"),
      LatexCommandSignature("\\Crefname{}{}{}"),
      LatexCommandSignature("\\DeclareAcronym{}{}"),
      LatexCommandSignature("\\DeclareCaptionFormat{}{}"),
      LatexCommandSignature("\\DeclareCaptionLabelFormat{}{}"),
      LatexCommandSignature("\\DeclareCiteCommand{}{}{}{}{}"),
      LatexCommandSignature("\\DeclareCiteCommand{}[]{}{}{}{}"),
      LatexCommandSignature("\\DeclareFieldFormat{}{}"),
      LatexCommandSignature("\\DeclareFieldFormat[]{}{}"),
      LatexCommandSignature("\\DeclareFieldFormat*{}{}"),
      LatexCommandSignature("\\DeclareGraphicsExtensions{}"),
      LatexCommandSignature("\\DeclareMathAlphabet{}{}{}{}{}"),
      LatexCommandSignature("\\DeclareMathOperator{}{}"),
      LatexCommandSignature("\\DeclareMathOperator*{}{}"),
      LatexCommandSignature("\\DeclareNameAlias{}{}"),
      LatexCommandSignature("\\DeclareNewTOC{}"),
      LatexCommandSignature("\\DeclareNewTOC[]{}"),
      LatexCommandSignature("\\DeclareSIUnit{}{}"),
      LatexCommandSignature("\\DeclareSIUnit[]{}{}"),
      LatexCommandSignature("\\declaretheorem{}"),
      LatexCommandSignature("\\declaretheorem[]{}"),
      LatexCommandSignature("\\declaretheoremstyle{}"),
      LatexCommandSignature("\\declaretheoremstyle[]{}"),
      LatexCommandSignature("\\DeclareTOCStyleEntry{}"),
      LatexCommandSignature("\\DeclareTOCStyleEntry[]{}{}"),
      LatexCommandSignature("\\defbibcheck{}{}"),
      LatexCommandSignature("\\defbibenvironment{}{}{}{}"),
      LatexCommandSignature("\\defbibfilter{}{}"),
      LatexCommandSignature("\\defbibheading{}{}"),
      LatexCommandSignature("\\defbibheading{}[]{}"),
      LatexCommandSignature("\\defbibnote{}{}"),
      LatexCommandSignature("\\definecolor{}{}{}"),
      LatexCommandSignature("\\definespotcolor{}{}{}"),
      LatexCommandSignature("\\directlua{}"),
      LatexCommandSignature("\\DisableLigatures{}"),
      LatexCommandSignature("\\documentclass{}"),
      LatexCommandSignature("\\documentclass[]{}"),
      LatexCommandSignature("\\email{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\enlargethispage{}"),
      LatexCommandSignature("\\eqref{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\etocsetlevel{}{}"),
      LatexCommandSignature("\\etocsetnexttocdepth{}"),
      LatexCommandSignature("\\etocsettocstyle{}{}"),
      LatexCommandSignature("\\fcolorbox{}"),
      LatexCommandSignature("\\floatname{}{}"),
      LatexCommandSignature("\\floatstyle{}"),
      LatexCommandSignature("\\footcite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\footcite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\footcite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\footcitetext{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\footcitetext[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\footcitetext[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\footnote{}"),
      LatexCommandSignature("\\footnote[]{}"),
      LatexCommandSignature(
        "\\foreignlanguage{}{}",
        LatexCommandSignature.Action.Dummy,
      ),
      LatexCommandSignature(
        "\\foreignlanguage[]{}{}",
        LatexCommandSignature.Action.Dummy,
      ),
      LatexCommandSignature("\\GenericWarning{}{}"),
      LatexCommandSignature("\\geometry{}"),
      LatexCommandSignature("\\gls{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Gls{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\glsaddstoragekey{}{}{}"),
      LatexCommandSignature("\\glsentryfull{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\glsentrylong{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\glsentryshort{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\glsentrytext{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\glsfmtshort{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature(
        "\\glspl{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Glspl{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature("\\glssymbol{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\GlsXtrLoadResources[]"),
      LatexCommandSignature("\\glsxtrnewsymbol{}{}"),
      LatexCommandSignature("\\glsxtrnewsymbol[]{}{}"),
      LatexCommandSignature("\\graphicspath{}"),
      LatexCommandSignature("\\hphantom{}"),
      LatexCommandSignature("\\href{}{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\hyperref[]"),
      LatexCommandSignature("\\hypersetup{}"),
      LatexCommandSignature("\\iac{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iac{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iac[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iac[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iac*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iac*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iac*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iac*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iaca{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iaca{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iaca[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iaca[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iaca*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iaca*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iaca*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iaca*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacf{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacf{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacf[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacf[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacf*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacf*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacf*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacf*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacl{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacl{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacl[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacl[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacl*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacl*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacl*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacl*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacs{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacs{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacs[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacs[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacs*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacs*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\iacs*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Iacs*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\ifcurrentfield{}"),
      LatexCommandSignature("\\ifentrytype{}"),
      LatexCommandSignature("\\@ifpackageloaded{}"),
      LatexCommandSignature("\\iftoggle{}"),
      LatexCommandSignature("\\include{}"),
      LatexCommandSignature("\\includegraphics{}"),
      LatexCommandSignature("\\includegraphics[]{}"),
      LatexCommandSignature("\\includepdf{}"),
      LatexCommandSignature("\\includepdf[]{}"),
      LatexCommandSignature("\\input{}"),
      LatexCommandSignature("\\inputminted{}{}"),
      LatexCommandSignature("\\inputminted[]{}{}"),
      LatexCommandSignature("\\KOMAoptions{}"),
      LatexCommandSignature("\\KOMAScript", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\label{}"),
      LatexCommandSignature("\\LaTeX", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\lettrine{}{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\lettrine[]{}{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\linespread{}"),
      LatexCommandSignature("\\loadglsentries{}"),
      LatexCommandSignature("\\longnewglossaryentry{}{}"),
      LatexCommandSignature("\\luadirect{}"),
      LatexCommandSignature("\\luaexec{}"),
      LatexCommandSignature("\\mdfdefinestyle{}{}"),
      LatexCommandSignature("\\mint{}{}"),
      LatexCommandSignature("\\mintinline{}{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\multicolumn{}{}"),
      LatexCommandSignature("\\multirow{}{}"),
      LatexCommandSignature("\\newabbreviation{}{}"),
      LatexCommandSignature("\\newabbreviation[]{}{}"),
      LatexCommandSignature("\\newacronym{}{}"),
      LatexCommandSignature("\\newacronym[]{}{}"),
      LatexCommandSignature("\\newboolean{}"),
      LatexCommandSignature("\\newcolumntype{}{}"),
      LatexCommandSignature("\\newcommand{}{}"),
      LatexCommandSignature("\\newcommand{}[]{}"),
      LatexCommandSignature("\\newcommand{}[][]{}"),
      LatexCommandSignature("\\newcommand*{}{}"),
      LatexCommandSignature("\\newcommand*{}[]{}"),
      LatexCommandSignature("\\newcommand*{}[][]{}"),
      LatexCommandSignature("\\newcounter{}"),
      LatexCommandSignature("\\newenvironment{}{}{}"),
      LatexCommandSignature("\\newenvironment{}[]{}{}"),
      LatexCommandSignature("\\newenvironment*{}{}{}"),
      LatexCommandSignature("\\newenvironment*{}[]{}{}"),
      LatexCommandSignature("\\newfloat{}{}{}"),
      LatexCommandSignature("\\newfloat{}{}{}[]"),
      LatexCommandSignature("\\newgeometry{}"),
      LatexCommandSignature("\\newglossary{}{}{}"),
      LatexCommandSignature("\\newglossary[]{}{}{}"),
      LatexCommandSignature("\\newglossary*{}"),
      LatexCommandSignature("\\newglossaryentry{}{}"),
      LatexCommandSignature("\\newglossarystyle{}{}"),
      LatexCommandSignature("\\newrefcontext[]"),
      LatexCommandSignature("\\newtheorem{}{}"),
      LatexCommandSignature("\\newtheorem{}{}[]"),
      LatexCommandSignature("\\newtheorem{}[]{}"),
      LatexCommandSignature("\\newtheorem{}[]{}[]"),
      LatexCommandSignature("\\newtheorem*{}{}"),
      LatexCommandSignature("\\newtoggle{}"),
      LatexCommandSignature("\\nolinkurl{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\numberwithin{}{}"),
      LatexCommandSignature("\\PackageWarning{}{}"),
      LatexCommandSignature("\\pagecolor{}"),
      LatexCommandSignature("\\pagenumbering{}"),
      LatexCommandSignature("\\pageref{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\pageref*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\pagestyle{}"),
      LatexCommandSignature("\\parencite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\parencite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\parencite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\parencite*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\parencite*[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\parencite*[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Parencite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Parencite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Parencite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\pdfbookmark{}{}"),
      LatexCommandSignature("\\pdfbookmark[]{}{}"),
      LatexCommandSignature("\\pgfdeclaredecoration{}{}{}"),
      LatexCommandSignature("\\pgfmathsetmacro{}{}"),
      LatexCommandSignature("\\pgfmathsetseed{}"),
      LatexCommandSignature("\\phantom{}"),
      LatexCommandSignature("\\printacronyms[]"),
      LatexCommandSignature("\\printbibliography[]"),
      LatexCommandSignature("\\printglossary[]"),
      LatexCommandSignature("\\printnoidxglossary[]"),
      LatexCommandSignature("\\printunsrtglossary[]"),
      LatexCommandSignature("\\providecommand{}{}"),
      LatexCommandSignature("\\providecommand{}[]{}"),
      LatexCommandSignature("\\providecommand*{}{}"),
      LatexCommandSignature("\\providecommand*{}[]{}"),
      LatexCommandSignature("\\raisebox{}"),
      LatexCommandSignature("\\RedeclareSectionCommand{}"),
      LatexCommandSignature("\\RedeclareSectionCommand[]{}"),
      LatexCommandSignature("\\RedeclareSectionCommands{}"),
      LatexCommandSignature("\\RedeclareSectionCommands[]{}"),
      LatexCommandSignature("\\ref{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\ref*{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\renewbibmacro{}{}"),
      LatexCommandSignature("\\renewbibmacro*{}{}"),
      LatexCommandSignature("\\renewcommand{}{}"),
      LatexCommandSignature("\\renewcommand{}[]{}"),
      LatexCommandSignature("\\renewcommand{}[][]{}"),
      LatexCommandSignature("\\renewcommand*{}{}"),
      LatexCommandSignature("\\renewcommand*{}[]{}"),
      LatexCommandSignature("\\renewcommand*{}[][]{}"),
      LatexCommandSignature("\\renewenvironment{}{}{}"),
      LatexCommandSignature("\\renewenvironment{}[]{}{}"),
      LatexCommandSignature("\\renewenvironment*{}{}{}"),
      LatexCommandSignature("\\renewenvironment*{}[]{}{}"),
      LatexCommandSignature("\\renewlist{}{}{}"),
      LatexCommandSignature("\\RequirePackage{}"),
      LatexCommandSignature("\\scalebox{}"),
      LatexCommandSignature("\\selectlanguage{}"),
      LatexCommandSignature("\\setabbreviationstyle{}"),
      LatexCommandSignature("\\setabbreviationstyle[]{}"),
      LatexCommandSignature("\\setacronymstyle{}"),
      LatexCommandSignature("\\setboolean{}"),
      LatexCommandSignature("\\setcopyright{}"),
      LatexCommandSignature("\\setcounter{}{}"),
      LatexCommandSignature("\\setenumerate{}"),
      LatexCommandSignature("\\setglossarystyle{}"),
      LatexCommandSignature("\\setitemize{}"),
      LatexCommandSignature("\\setkomafont{}{}"),
      LatexCommandSignature("\\setkomavar{}"),
      LatexCommandSignature("\\setkomavar{}[]"),
      LatexCommandSignature("\\setkomavar*{}"),
      LatexCommandSignature("\\setkomavar*{}[]"),
      LatexCommandSignature("\\setlength{}{}"),
      LatexCommandSignature("\\setlist{}"),
      LatexCommandSignature("\\setlist[]{}"),
      LatexCommandSignature("\\SetMathAlphabet{}{}{}{}{}{}"),
      LatexCommandSignature("\\setmainfont{}"),
      LatexCommandSignature("\\setmainfont{}[]"),
      LatexCommandSignature("\\setparsizes{}{}{}"),
      LatexCommandSignature("\\@setplength{}{}"),
      LatexCommandSignature("\\setplength{}{}"),
      LatexCommandSignature("\\setstretch{}"),
      LatexCommandSignature("\\setuptoc{}{}"),
      LatexCommandSignature("\\sisetup{}"),
      LatexCommandSignature("\\smartcite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\smartcite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\smartcite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Smartcite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Smartcite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Smartcite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\stepcounter{}"),
      LatexCommandSignature("\\supercite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\SweaveInput{}"),
      LatexCommandSignature("\\SweaveOpts{}"),
      LatexCommandSignature("\\SweaveSyntax{}"),
      LatexCommandSignature("\\TeX", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\textcite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\textcite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\textcite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Textcite{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Textcite[]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\Textcite[][]{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature(
        "\\textcites{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\textcites{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\textcites{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\textcites{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\textcites{}{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\textcites()()[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\textcites()()[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\textcites()()[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\textcites()()[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\textcites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites{}{}{}{}{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites()()[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites()()[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites()()[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites()()[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature(
        "\\Textcites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
        LatexCommandSignature.Action.Dummy,
        DummyGenerator.getInstance(plural = true),
      ),
      LatexCommandSignature("\\textcolor{}"),
      LatexCommandSignature("\\textcolor[]{}"),
      LatexCommandSignature("\\textproc{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\theoremstyle{}"),
      LatexCommandSignature("\\thispagestyle{}"),
      LatexCommandSignature("\\tikz{}"),
      LatexCommandSignature("\\tikzset{}"),
      LatexCommandSignature("\\todo{}"),
      LatexCommandSignature("\\todo[]{}"),
      LatexCommandSignature("\\togglefalse{}"),
      LatexCommandSignature("\\toggletrue{}"),
      LatexCommandSignature("\\unsettoc{}{}"),
      LatexCommandSignature("\\url{}", LatexCommandSignature.Action.Dummy),
      LatexCommandSignature("\\usebibmacro{}"),
      LatexCommandSignature("\\usekomafont{}"),
      LatexCommandSignature("\\usemintedstyle{}"),
      LatexCommandSignature("\\usepackage{}"),
      LatexCommandSignature("\\usepackage[]{}"),
      LatexCommandSignature("\\usetikzlibrary{}"),
      LatexCommandSignature("\\value{}"),
      LatexCommandSignature("\\vphantom{}"),
      LatexCommandSignature("\\vspace{}"),
      LatexCommandSignature("\\vspace*{}"),
      LatexCommandSignature("\\WarningFilter{}{}"),
    )

    val babelLanguageMap: Map<String, String> = LatexFragmentizer.BABEL_LANGUAGE_MAP

    for (language in babelLanguageMap.keys) {
      val languageTag: String = LatexFragmentizer.convertBabelLanguageToLanguageTag(language)
      list.add(LatexCommandSignature("\\text$languageTag{}", LatexCommandSignature.Action.Dummy))
    }

    list
  }

  val defaultLatexEnvironmentSignatures: List<LatexEnvironmentSignature> = run {
    val list: MutableList<LatexEnvironmentSignature> = mutableListOf(
      LatexEnvironmentSignature("\\begin{frame}", LatexCommandSignature.Action.Default),
      LatexEnvironmentSignature("lstlisting"),
      LatexEnvironmentSignature("minted"),
      LatexEnvironmentSignature("otherlanguage"),
      LatexEnvironmentSignature("otherlanguage*"),
      LatexEnvironmentSignature("textpos"),
      LatexEnvironmentSignature("textpos*"),
      LatexEnvironmentSignature("tikzpicture"),
      LatexEnvironmentSignature("verbatim"),
    )

    val babelLanguageMap: Map<String, String> = LatexFragmentizer.BABEL_LANGUAGE_MAP
    for (language in babelLanguageMap.keys) {
      val languageTag: String = LatexFragmentizer.convertBabelLanguageToLanguageTag(language)
      list.add(LatexEnvironmentSignature(language))
      if (languageTag.length != language.length) list.add(LatexEnvironmentSignature(languageTag))
    }

    list
  }
}
