package org.bsplines.ltexls.parsing.latex;

import org.bsplines.ltexls.parsing.DummyGenerator;

class DefaultLatexCommandSignatures {
  private static final LatexCommandSignature[] list = {
      new LatexCommandSignature("\\addbibresource{}"),
      new LatexCommandSignature("\\addtocontents{}"),
      new LatexCommandSignature("\\addtocounter{}{}"),
      new LatexCommandSignature("\\addtokomafont{}{}"),
      new LatexCommandSignature("\\addtotheorempostheadhook{}"),
      new LatexCommandSignature("\\addxcontentsline{}{}{}"),
      new LatexCommandSignature("\\algdef{}[]{}{}"),
      new LatexCommandSignature("\\algnewcommand{}{}"),
      new LatexCommandSignature("\\algrenewcommand{}{}"),
      new LatexCommandSignature("\\arabic{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\AtBeginEnvironment{}{}"),
      new LatexCommandSignature("\\AtEndEnvironment{}{}"),
      new LatexCommandSignature("\\autopageref{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\autopageref*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\autoref{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\autoref*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\bibitem{}"),
      new LatexCommandSignature("\\bibliography{}"),
      new LatexCommandSignature("\\bibliographystyle{}"),
      new LatexCommandSignature("\\captionof{}"),
      new LatexCommandSignature("\\captionsetup{}"),
      new LatexCommandSignature("\\captionsetup[]{}"),
      new LatexCommandSignature("\\cite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\cite[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\cite[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Cite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Cite[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Cite[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\cite*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\cite*[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\cite*[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citealp{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citealp[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citealp*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citealp*[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citealt{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citealt[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citealt*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citealt*[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citep{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citep[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citep*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citep*[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\cites{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\cites{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\cites{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\cites{}{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\cites{}{}{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\cites()()[][]{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\cites()()[][]{}[][]{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\cites()()[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\cites()()[][]{}[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\cites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites{}{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites{}{}{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites()()[][]{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites()()[][]{}[][]{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites()()[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites()()[][]{}[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Cites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\citet{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citet[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citet*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\citet*[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\clearfield{}"),
      new LatexCommandSignature("\\cref{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Cref{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\crefname{}{}{}"),
      new LatexCommandSignature("\\Crefname{}{}{}"),
      new LatexCommandSignature("\\DeclareCaptionFormat{}{}"),
      new LatexCommandSignature("\\DeclareCaptionLabelFormat{}{}"),
      new LatexCommandSignature("\\DeclareCiteCommand{}{}{}{}{}"),
      new LatexCommandSignature("\\DeclareCiteCommand{}[]{}{}{}{}"),
      new LatexCommandSignature("\\DeclareFieldFormat{}{}"),
      new LatexCommandSignature("\\DeclareFieldFormat[]{}{}"),
      new LatexCommandSignature("\\DeclareGraphicsExtensions{}"),
      new LatexCommandSignature("\\DeclareMathAlphabet{}{}{}{}{}"),
      new LatexCommandSignature("\\DeclareMathOperator{}{}"),
      new LatexCommandSignature("\\DeclareMathOperator*{}{}"),
      new LatexCommandSignature("\\DeclareNameAlias{}{}"),
      new LatexCommandSignature("\\DeclareNewTOC{}"),
      new LatexCommandSignature("\\DeclareNewTOC[]{}"),
      new LatexCommandSignature("\\declaretheorem{}"),
      new LatexCommandSignature("\\declaretheorem[]{}"),
      new LatexCommandSignature("\\declaretheoremstyle{}"),
      new LatexCommandSignature("\\declaretheoremstyle[]{}"),
      new LatexCommandSignature("\\DeclareTOCStyleEntry{}"),
      new LatexCommandSignature("\\DeclareTOCStyleEntry[]{}{}"),
      new LatexCommandSignature("\\defbibheading{}{}"),
      new LatexCommandSignature("\\defbibheading{}[]{}"),
      new LatexCommandSignature("\\defbibnote{}{}"),
      new LatexCommandSignature("\\definecolor{}{}{}"),
      new LatexCommandSignature("\\DisableLigatures{}"),
      new LatexCommandSignature("\\documentclass{}"),
      new LatexCommandSignature("\\documentclass[]{}"),
      new LatexCommandSignature("\\email{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\eqref{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\etocsetnexttocdepth{}"),
      new LatexCommandSignature("\\etocsettocstyle{}{}"),
      new LatexCommandSignature("\\floatname{}{}"),
      new LatexCommandSignature("\\floatstyle{}"),
      new LatexCommandSignature("\\footcite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\footcite[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\footcite[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\footcitetext{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\footcitetext[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\footcitetext[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\footnote{}"),
      new LatexCommandSignature("\\footnote[]{}"),
      new LatexCommandSignature("\\foreignlanguage{}{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\GenericWarning{}{}"),
      new LatexCommandSignature("\\geometry{}"),
      new LatexCommandSignature("\\glsaddstoragekey{}{}{}"),
      new LatexCommandSignature("\\graphicspath{}"),
      new LatexCommandSignature("\\href{}{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\hyperref[]"),
      new LatexCommandSignature("\\hypersetup{}"),
      new LatexCommandSignature("\\ifcurrentfield{}"),
      new LatexCommandSignature("\\ifentrytype{}"),
      new LatexCommandSignature("\\iftoggle{}"),
      new LatexCommandSignature("\\include{}"),
      new LatexCommandSignature("\\includegraphics{}"),
      new LatexCommandSignature("\\includegraphics[]{}"),
      new LatexCommandSignature("\\includepdf{}"),
      new LatexCommandSignature("\\includepdf[]{}"),
      new LatexCommandSignature("\\input{}"),
      new LatexCommandSignature("\\KOMAoptions{}"),
      new LatexCommandSignature("\\KOMAScript", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\label{}"),
      new LatexCommandSignature("\\LaTeX", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\lettrine{}{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\lettrine[]{}{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\linespread{}"),
      new LatexCommandSignature("\\luadirect{}"),
      new LatexCommandSignature("\\luaexec{}"),
      new LatexCommandSignature("\\mdfdefinestyle{}{}"),
      new LatexCommandSignature("\\multicolumn{}{}"),
      new LatexCommandSignature("\\multirow{}{}"),
      new LatexCommandSignature("\\newboolean{}"),
      new LatexCommandSignature("\\newcolumntype{}{}"),
      new LatexCommandSignature("\\newcommand{}{}"),
      new LatexCommandSignature("\\newcommand{}[]{}"),
      new LatexCommandSignature("\\newcommand*{}{}"),
      new LatexCommandSignature("\\newcommand*{}[]{}"),
      new LatexCommandSignature("\\newcounter{}"),
      new LatexCommandSignature("\\newenvironment{}{}{}"),
      new LatexCommandSignature("\\newenvironment{}[]{}{}"),
      new LatexCommandSignature("\\newenvironment*{}{}{}"),
      new LatexCommandSignature("\\newenvironment*{}[]{}{}"),
      new LatexCommandSignature("\\newfloat{}{}{}"),
      new LatexCommandSignature("\\newfloat{}{}{}[]"),
      new LatexCommandSignature("\\newgeometry{}"),
      new LatexCommandSignature("\\newglossaryentry{}{}"),
      new LatexCommandSignature("\\newglossarystyle{}{}"),
      new LatexCommandSignature("\\newtheorem{}{}"),
      new LatexCommandSignature("\\newtheorem*{}{}"),
      new LatexCommandSignature("\\newtoggle{}"),
      new LatexCommandSignature("\\nolinkurl{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\PackageWarning{}{}"),
      new LatexCommandSignature("\\pagenumbering{}"),
      new LatexCommandSignature("\\pageref{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\pageref*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\pagestyle{}"),
      new LatexCommandSignature("\\parencite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\parencite[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\parencite[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\parencite*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\parencite*[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\parencite*[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Parencite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Parencite[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Parencite[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\pdfbookmark{}{}"),
      new LatexCommandSignature("\\pdfbookmark[]{}{}"),
      new LatexCommandSignature("\\pgfdeclaredecoration{}{}{}"),
      new LatexCommandSignature("\\pgfmathsetseed{}"),
      new LatexCommandSignature("\\printbibliography[]"),
      new LatexCommandSignature("\\printglossary[]"),
      new LatexCommandSignature("\\providecommand{}{}"),
      new LatexCommandSignature("\\providecommand{}[]{}"),
      new LatexCommandSignature("\\providecommand*{}{}"),
      new LatexCommandSignature("\\providecommand*{}[]{}"),
      new LatexCommandSignature("\\raisebox{}"),
      new LatexCommandSignature("\\RedeclareSectionCommand{}"),
      new LatexCommandSignature("\\RedeclareSectionCommand[]{}"),
      new LatexCommandSignature("\\RedeclareSectionCommands{}"),
      new LatexCommandSignature("\\RedeclareSectionCommands[]{}"),
      new LatexCommandSignature("\\ref{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\ref*{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\renewbibmacro{}{}"),
      new LatexCommandSignature("\\renewbibmacro*{}{}"),
      new LatexCommandSignature("\\renewcommand{}{}"),
      new LatexCommandSignature("\\renewcommand{}[]{}"),
      new LatexCommandSignature("\\renewcommand*{}{}"),
      new LatexCommandSignature("\\renewcommand*{}[]{}"),
      new LatexCommandSignature("\\renewenvironment{}{}{}"),
      new LatexCommandSignature("\\renewenvironment{}[]{}{}"),
      new LatexCommandSignature("\\renewenvironment*{}{}{}"),
      new LatexCommandSignature("\\renewenvironment*{}[]{}{}"),
      new LatexCommandSignature("\\RequirePackage{}"),
      new LatexCommandSignature("\\scalebox{}"),
      new LatexCommandSignature("\\setboolean{}"),
      new LatexCommandSignature("\\setcopyright{}"),
      new LatexCommandSignature("\\setcounter{}{}"),
      new LatexCommandSignature("\\setenumerate{}"),
      new LatexCommandSignature("\\setglossarystyle{}"),
      new LatexCommandSignature("\\setitemize{}"),
      new LatexCommandSignature("\\setkomafont{}{}"),
      new LatexCommandSignature("\\setkomavar{}{}"),
      new LatexCommandSignature("\\setkomavar{}[]{}"),
      new LatexCommandSignature("\\setkomavar*{}{}"),
      new LatexCommandSignature("\\setkomavar*{}[]{}"),
      new LatexCommandSignature("\\setlength{}{}"),
      new LatexCommandSignature("\\setlist{}"),
      new LatexCommandSignature("\\SetMathAlphabet{}{}{}{}{}{}"),
      new LatexCommandSignature("\\@setplength{}{}"),
      new LatexCommandSignature("\\setstretch{}"),
      new LatexCommandSignature("\\sisetup{}"),
      new LatexCommandSignature("\\smartcite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\smartcite[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\smartcite[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Smartcite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Smartcite[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Smartcite[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\stepcounter{}"),
      new LatexCommandSignature("\\supercite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\SweaveInput{}"),
      new LatexCommandSignature("\\SweaveOpts{}"),
      new LatexCommandSignature("\\SweaveSyntax{}"),
      new LatexCommandSignature("\\TeX", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\textcite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\textcite[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\textcite[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Textcite{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Textcite[]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\Textcite[][]{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\textcites{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcites{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcites{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcites{}{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcites{}{}{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcites()()[][]{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcites()()[][]{}[][]{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcites()()[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcites()()[][]{}[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites{}{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites{}{}{}{}{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites()()[][]{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites()()[][]{}[][]{}", LatexCommandSignature.Action.DUMMY,
          DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites()()[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites()()[][]{}[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\Textcites()()[][]{}[][]{}[][]{}[][]{}[][]{}",
          LatexCommandSignature.Action.DUMMY, DummyGenerator.getDefault(true)),
      new LatexCommandSignature("\\textcolor{}"),
      new LatexCommandSignature("\\textproc{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\thispagestyle{}"),
      new LatexCommandSignature("\\tikz{}"),
      new LatexCommandSignature("\\tikzset{}"),
      new LatexCommandSignature("\\todo{}"),
      new LatexCommandSignature("\\todo[]{}"),
      new LatexCommandSignature("\\togglefalse{}"),
      new LatexCommandSignature("\\toggletrue{}"),
      new LatexCommandSignature("\\url{}", LatexCommandSignature.Action.DUMMY),
      new LatexCommandSignature("\\usebibmacro{}"),
      new LatexCommandSignature("\\usekomafont{}"),
      new LatexCommandSignature("\\usepackage{}"),
      new LatexCommandSignature("\\usepackage[]{}"),
      new LatexCommandSignature("\\usetikzlibrary{}"),
      new LatexCommandSignature("\\value{}"),
      new LatexCommandSignature("\\vspace{}"),
      new LatexCommandSignature("\\vspace*{}"),
      new LatexCommandSignature("\\WarningFilter{}{}"),
      };

  private DefaultLatexCommandSignatures() {
  }

  public static LatexCommandSignature[] get() {
    return list;
  }
}
